### ISSUE TITLE
task checks  even if not started

### ISSUE THREAD

**Issue by JuliaGloggPete** [zocom-azomo/azomo#1]
**Describe the bug**
If you click on Inte påbörjat it still checks the box green on a task

**Expected behavior**
I think it is missleading and should not happen

![Skärmavbild 2023-08-29 kl  10 02 34](https://github.com/zocom-azomo/azomo/assets/113100420/79f28a94-16de-47a8-9c26-0d47a0252654)

**Comment by zocom-johan-kivi** [comment]
Tack för feedbacken Julia! 
Den bör inte skicka iväg en request om du klickar på "ej påbörjat". Det är en bug, och jag löser den inom kort!

**Comment by zocom-johan-kivi** [comment]
Fixat och pushat. Bör synas i produktion inom några minuter.
