### ISSUE TITLE
Lägga till länkar på en hel kurs

### ISSUE THREAD

**Issue by lejonmanen** [zocom-azomo/azomo#10]
Möjlighet att lägga till länkar som ligger på "kurstitelnivå". T.ex. **schema**, **länk till GitHub-organisation** osv. Sådant som liksom inte passar i en specifik aktivitet.

En ruta direkt under kursmålen skulle passa bra.

En workaround är att lägga sådana länkar i första lärområdet. En annan att skriva i den korta kursbeskrivningen, men den tror jag är begränsad till antalet tecken.

**Comment by zocom-johan-kivi** [comment]
Fixat i 2.1.
