### ISSUE TITLE
Feedback till student klipps av om den är för lång

### ISSUE THREAD

**Issue by lejonmanen** [zocom-azomo/azomo#100]
När jag som lärare ger lite längre feedback till en student, så dyker det inte upp något sätt att scrolla texten. Studenten kan bara se en del av feedbacken, ca 15 ord.

**Comment by zocom-christoffer-wallenberg** [comment]
Fixad och redo för release.

**Comment by zocom-christoffer-wallenberg** [comment]
Fix finns i produktion.
