### ISSUE TITLE
Kan inte avpublicera kurs

### ISSUE THREAD

**Issue by lejonmanen** [zocom-azomo/azomo#18]
När man väl har valt att publicera en kurs, går det inte att ångra sig. Det ser ut som att "publicera" slidern är klickbar, men det händer inget när jag klickar på den.

Lösningsförslag: lägg till avpublicera-funktionen, eller ta bort slidern helt och ersätt med texten "Kursen är publicerad".

**Comment by zocom-johan-kivi** [comment]
Verkar vara en backend-bug. Är den på spåren!

**Comment by zocom-johan-kivi** [comment]
Fixad och pushad. Uppdateras i produktionsmiljön senare idag.
