### ISSUE TITLE
Ändringar i en kurs uppdateras inte

### ISSUE THREAD

**Issue by lejonmanen** [zocom-azomo/azomo#19]
Jag gjorde ändringar i en kurs och gick tillbaka till "mina kurser". Ändringarna visades inte förrän jag laddade om sidan.

**Comment by zocom-johan-kivi** [comment]
Låter som något med cachen. Du gjorde ändringar i planeringsvyn? Sen klickade på "mina kurser" och där återfanns inte ändringen i kurstitel eller dyl?

**Comment by lejonmanen** [comment]
Ja, exakt. Tror att jag ändrade just kurstiteln. Du kanske missat att updatera store när man lämnar fältet? Och bara ändrar lokal state?

**Comment by zocom-johan-kivi** [comment]
Lyckas inte återskapa denna, får kika närmare tillsammans,

**Comment by zocom-johan-kivi** [comment]
troligtvis löst i 2.1 då rubbet ( inkl update function ) är helt omarbetad.

**Comment by lejonmanen** [comment]
Inte löst i azomo.dev. Jag ändrade "Titel" på planeringsvyn. Klickade sedan på hamburgaren och "Kurser". Kursen visas med gamla titeln.
