### ISSUE TITLE
Man kan inte boka av i fall man har klickat på påbörjat 

### ISSUE THREAD

**Issue by JuliaGloggPete** [zocom-azomo/azomo#2]
**Describe the bug**
tidigare bug beter sig nu annorlunda, se videon, jag kan aldrig trycker på ej påbörjat. Sidenote: Annars tycker jag att Azomo blivit mycket smidigare att navigera och är mycket mer överskådligt - toppen

**Desktop (please complete the following information):**
 - OS: IOS
 - Browser Safari
**Additional context**

https://github.com/zocom-azomo/azomo/assets/113100420/a5324c96-498e-442a-9011-5202649188f2

**Comment by zocom-johan-kivi** [comment]
Jag kikar upp under dagen! 👍

**Comment by zocom-johan-kivi** [comment]
fixad. pushas idag 2 okt.
