### ISSUE TITLE
Fel språk i felmeddelande "No Examinations found"

### ISSUE THREAD

**Issue by lejonmanen** [zocom-azomo/azomo#20]
När man jobbar med en kurs, innan man lagt upp några examinationer, visas felmeddelanden "No Examinations found". Det kan till exempel stå "Inga examinationer inlagda" i stället.

**Comment by zocom-johan-kivi** [comment]
Detta finns på flera ställen. Vanligaste "caset" är att felmeddelande som generas på backend är på engelska. Kommer åtgärdas i framtiden, men kan dröja lite.

**Comment by zocom-johan-kivi** [comment]
Samtliga frontend meddelanden är nu uteslutande på svenska. Servergenererade AWS-fel är på engelska.
