### ISSUE TITLE
Azomo visar ett meddelande om man har tomma dagar

### ISSUE THREAD

**Issue by lejonmanen** [zocom-azomo/azomo#24]
I normala fall ska det finnas en lärmodul eller examination för varje kalenderarbetsdag. Om det finns en dag utan modul, så skulle Azomo kunna visa ett meddelande: "Det finns dagar som inte har någon aktivitet", plus en lista på datumen.

**Comment by zocom-johan-kivi** [comment]
Pushat till dev. Redo för release.

**Comment by zocom-christoffer-wallenberg** [comment]
Pushad och ute i produktion.
