### ISSUE TITLE
Rubrik för konkreta lärmål i lärområdesvyn

### ISSUE THREAD

**Issue by lejonmanen** [zocom-azomo/azomo#26]
Lägg till en rubrik för konkreta lärmål i lärområdesvyn: "Mål för lärområdet"
Som det är nu ser studenterna bara "taggarna" för lärmålen. En enkel rubrik gör det lättare att förstå poängen.

**Comment by zocom-johan-kivi** [comment]
fixat

**Comment by lejonmanen** [comment]
Bara fixat i planeringsvyn, inte i kursvyn?
