### ISSUE TITLE
Ikon på betyg försvinner 

### ISSUE THREAD

**Issue by Oscar-Mattsson-790** [zocom-azomo/azomo#3]
**Describe the bug**
När man markerar en kurs så får man upp förhandsvyn och om man sedan väljer en annan kurs så försvinner betyget på listan. Dock så är dem tillbaka när man refreshar sidan

**Screenshots**
![Screenshot 2023-08-30 at 16 24 03](https://github.com/zocom-azomo/azomo/assets/60174332/910a2f45-de7d-41a6-8a34-758416114811)

**Desktop (please complete the following information):**
 - OS: MacBook Pro
 - Browser chrome
 - Version 116.0.5845.110 (Official Build) (x86_64)

**Comment by zocom-johan-kivi** [comment]
Tackar för bugrapport! Ska se vad detta konstiga beteende kan bero på. Låter som det är ett cache-problem. :D

**Comment by zocom-johan-kivi** [comment]
Har nu löst detta. Buggen satt längre in är jag trodde! Bör fungera enligt plan from imorgon 11/10.

**Comment by Oscar-Mattsson-790** [comment]
Hejsan,

Jag testade precis. Buggen kvarstår.
![Screenshot 2023-10-10 at 15 30 56](https://github.com/zocom-azomo/azomo/assets/60174332/bd3ab3ce-456c-4181-872b-523241249020)

**Comment by Oscar-Mattsson-790** [comment]
ok då testar vi imorgon :)

**Comment by Oscar-Mattsson-790** [comment]
Funkar :)
