### ISSUE TITLE
Kunna flytta skapade lärområden eller examinationer

### ISSUE THREAD

**Issue by AlvaroForesti** [zocom-azomo/azomo#35]
**Is your feature request related to a problem? Please describe.**
Ja, det skapar dubbelarbete att behöva radera en hel modul om man råkat lägga den med fel startdatum.

**Describe the solution you'd like**
Göra det möjligt att ändra startdatum för en befintlig modul, på samma sätt som det går att ändra slutdatum/tid.

**Describe alternatives you've considered**
De enda två alternativ jag ser är att antingen låta det stå fel i Azomo och riskera förvirring, eller radera hela modulen och sedan skapa den igen. Inget av alternativen är bra, men det blir ju av naturliga skäl alltid alternativ 2, som tar en del extratid.

**Additional context**
Hör av dig på Slack om jag missat någon alternativ lösning eller om jag har varit otydlig

**Comment by zocom-johan-kivi** [comment]
Går att flytta lärområden / examinationer i v2.1. Dock kan man fortfarande ej områden saker parallellt.
