### ISSUE TITLE
Sortera/filtrera kurser i kursvy

### ISSUE THREAD

**Issue by lejonmanen** [zocom-azomo/azomo#38]
Efter ett tag kommer det bli många kurser på Azomo. Jag har behov av att kunna sortera och filtrera. Use case:
1. Se vilken klass som en kurs hör till, direkt i kursvyn
2. Visa startdatum för respektive kurs. 
3. Visa bara kurser för en viss klass
4. Sortera kurser fallande på startdatum. (Den viktigaste är den som pågår, eller den som börjar snart. Det är okej att scrolla för att se gamla kurser.)
5. Sökfält där man kan skriva in del av kursnamn. Bara kurser där söktermen återfinns i kursnamn (eller beskrivning?) visas.
6. Dölja avslutade kurser. (En inställning typ checkbox)

**Comment by zocom-johan-kivi** [comment]
Kommer inom kort i v2.1.

**Comment by zocom-johan-kivi** [comment]
Delvis implementerat i 2.1 nu. Kanske duger? Sparar resten av förslagen på "nice to have".

**Comment by lejonmanen** [comment]
Vad innebär "delvis"?

**Comment by zocom-johan-kivi** [comment]
Fixat
