### ISSUE TITLE
Lägga till alternativ vid röstning

### ISSUE THREAD

**Issue by lejonmanen** [zocom-azomo/azomo#42]
En student efterlyste ett alternativ mellan "Förstår inte" och "Förstår mycket". Jag föreslår i första hand att lägga till alternativet "Förstår lite" emellan. I andra hand att byta namn på "Förstår mycket" till "Förstår en del".

![image](https://github.com/zocom-azomo/azomo/assets/1112045/d3a26c56-75f1-418f-93c2-408884f25ed1)

**Comment by zocom-christoffer-wallenberg** [comment]
Duplicering av #47 så stänger denna.
