### ISSUE TITLE
Synliggöra kursmålen för de studerande

### ISSUE THREAD

**Issue by AlvaroForesti** [zocom-azomo/azomo#43]
**Is your feature request related to a problem? Please describe.**
EGentligen inget direkt problem, utan bara för att vara tydlig. Kursmålen behöver vara tillgängliga för de studerande, inte enbart lärandemålen.

**Describe the solution you'd like**
Samma "modul" som läraren har i planeringsvyn med kursmålen från kursplanen syns längst upp även för de studerande.

**Describe alternatives you've considered**
Inga andra egentliga förslag, men är öppen för andra lösningar. Dock viktigt att inte enbart lärandemål syns, utan även de faktiska kursmålen.

**Additional context**
Request från FU

**Comment by zocom-johan-kivi** [comment]
Fixat i 2.1
