### ISSUE TITLE
Skapa kurser med 0 poäng

### ISSUE THREAD

**Issue by AlvaroForesti** [zocom-azomo/azomo#45]
**Is your feature request related to a problem? Please describe.**
Möjlighet att skapa kurser med 0 poäng, exempelvis för att lägga upp information om LIA.

**Describe the solution you'd like**
Möjlighet att skapa kurser med 0 poäng och till stor del syftar till att kunna lägga upp information.

**Describe alternatives you've considered**
Helt öppen för andra alternativ. Osäker på hur, men det kan man nog tänka kreativt kring tillsammans med våra kunder.

**Additional context**
Request från FU

**Comment by zocom-johan-kivi** [comment]
Fixat i 2.1
