### ISSUE TITLE
Ändra vh på <section class="program__intro"></section>

### ISSUE THREAD

**Issue by PlooJompong** [zocom-azomo/azomo#48]
Det är ingen bugg, jag vill bara ge förslag på att ändra viewport height på <section class="program__intro"></section> från 100vh till 20-30vh.

Jag tycker att det jobbig att man ska behöva scrolla ner för att se innehållet. Tycker att det ge bättre UX om man kommer direkt till det man vill åt.

![Current 100vh](https://github.com/zocom-azomo/azomo/assets/50630228/9e3419b4-f545-4a74-8f40-9b5096c03d05)

![20vh](https://github.com/zocom-azomo/azomo/assets/50630228/08037f85-ad49-4220-abaf-eb47698380d0)

**Comment by zocom-johan-kivi** [comment]
redesignat i 2.1
