### ISSUE TITLE
Lärmål

### ISSUE THREAD

**Issue by rachel-zocom** [zocom-azomo/azomo#5]
Det går inte att ändra lärmål (jag måste göra en ny för ändringar).

Det hade varit super om det gick att redigera/ändra genom att klicka på lärmål så att pop-upen som kommer upp när man ska 
lägga till ett lärmål kommer upp, men med redigeringsmöjligheter (t ex ändra vilka kursmål som är kopplade till lärmålet eller 
fixa stavning)

**Comment by zocom-johan-kivi** [comment]
Ja, så har det fungerat! 😓  Jag kikar upp bugg!

**Comment by zocom-johan-kivi** [comment]
Fixat i 2.1
