### ISSUE TITLE
Fel i saknade inlämningar

### ISSUE THREAD

**Issue by lejonmanen** [zocom-azomo/azomo#51]
Under lärarvyn för inlämnade examinationer visas vilka studenter som inte lämnat in uppgiften, under rubriken "Saknade", visas både studenter och lärare.
![image](https://github.com/zocom-azomo/azomo/assets/1112045/0f312021-245f-4ebf-9dd5-994db25ff629)

**Comment by zocom-johan-kivi** [comment]
Fixat i v2.1, kommer inom kort.
