### ISSUE TITLE
Sortera inlämnade examinationer

### ISSUE THREAD

**Issue by lejonmanen** [zocom-azomo/azomo#52]
Inlämnade examinationer verkar visas i slumpmässig ordning. Jag skulle önska att man som lärare kunde toggla mellan sorteringar:

1. stigande på datum (så kan läraren lättare se vilka som lämnat in tidigt, och rätta deras inlämning först)
2. bokstavsordning på efternamn
3. bokstavsordning på förnamn

Om man behöver synka studenternas namn med något annat system, skulle det underlätta att kunna sortera efter namn. Det är inte alltid som andra system använder efternamnet i första hand.

**Comment by lejonmanen** [comment]
Lärare visas under kursbetyg också. Här bör studenterna sorteras på namn.

**Comment by zocom-christoffer-wallenberg** [comment]
Stänger denna då den arbetas på, se bugg #72 .
