### ISSUE TITLE
Visuell återkoppling på självskattning

### ISSUE THREAD

**Issue by lejonmanen** [zocom-azomo/azomo#55]
Flera studenter har inte fyllt i självskattningen. Jag har fått indikationer på "jag trodde jag var klar" när man antingen har skattat aktiviteterna, eller klickat på "Lets uppskatta vad jag lärt mig". Det behöver bli tydligare när man inte har gjort klart alla delar.

Förslag A: en banner högst upp på sidan talar om ifall man inte gjort alla självskattningar man ska göra.

Förslag B: om slutdatum för en modul är passerat, så visas en emoji till vänster om texten.
![mockup-självskattning](https://github.com/zocom-azomo/azomo/assets/1112045/519f989f-3897-4744-9088-e63d9d8822f7)

⚠️✔️👍

**Comment by zocom-johan-kivi** [comment]
Finns idag ( i form av att aktiviteten blir grön och får en bock ), förtydligas inom kort i v2.1.
