### ISSUE TITLE
Overlap between modals on the homepage.

### ISSUE THREAD

**Issue by Mercenaress** [zocom-azomo/azomo#58]
**Describe the bug**
When opening the course modules on the homepage the bottom of the extended modal overlaps with the closed ones. Alternatively the modal has a huge gap if it's small when open. 

**To Reproduce**
1. Go to https://azomo.io/me
2. Click on the course modals.
3. Scroll down to the bottom of the modal.

**Expected behavior**
I expect it to look readable and not overlap.

**Screenshots**
![image](https://github.com/zocom-azomo/azomo/assets/116269114/787a296e-e291-41d8-9573-20a0a1b5b3a7)
![image](https://github.com/zocom-azomo/azomo/assets/116269114/6e0bfd9d-7a98-4289-9dc0-0d8d49ba1013)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 119.0.6045.200

**Additional context**

**Comment by zocom-johan-kivi** [comment]
Tackar! Det är något fel i pixeluträkningen som räknar ut höjden! Räknar om dom, fast mycket noggrannare! :D

**Comment by zocom-johan-kivi** [comment]
Kika nu, borde vara fixat. Ser bra ut i dev-miljön, men det är det inte riktigt lika många kurser som kan påverka.

**Comment by Mercenaress** [comment]
Nu funkar dem kortare modulerna bra men de långa får fortfarande lite overlap, upplösningen påverkar inte vad jag kan se. Har testat på båda mina skärmar den ena 1440p och den andra 1080p. 

You've got this! c:

![image](https://github.com/zocom-azomo/azomo/assets/116269114/74699e5c-6084-4a87-9224-68366a47d137)
![image](https://github.com/zocom-azomo/azomo/assets/116269114/47005203-7601-42bb-99a3-e4227b1d34b2)

**Comment by zocom-johan-kivi** [comment]
Tack för återkoppling! Då har jag missat någon mer pixel! Räknar igen och återkommer! :D

**Comment by zocom-johan-kivi** [comment]
Fixad och pushad.
