### ISSUE TITLE
Självskattning klar trots "Ej påbörjat"

### ISSUE THREAD

**Issue by justinhumane** [zocom-azomo/azomo#59]
**Describe the bug**
Om man öppnar en aktivitet och väljer något av alternativen i självskattningen men sedan vill ändra sig och gå tillbaka till "Ej påbörjat"-alternativet anser Azomo att självskattningen för den aktiviteten är klar. 

**To Reproduce**
1. Öppna aktivitet
2. Välj något av självskattningsalternativen
3. Stäng aktivitet
4. Öppna aktivitet
5. Välj "Ej påbörjat"

**Expected behavior**
Om man självskattar att man inte påbörjat aktiviteten borde Azomo förstå att aktiviteten inte är klar.

**Screenshots**
![image](https://github.com/zocom-azomo/azomo/assets/86984290/a7b45636-bdbf-4d41-b5f9-b255568384fe)
![image](https://github.com/zocom-azomo/azomo/assets/86984290/99d7c645-1387-40b8-b0f1-e681c91862aa)

**Comment by zocom-christoffer-wallenberg** [comment]
Redo för release.

**Comment by zocom-christoffer-wallenberg** [comment]
Pushad och ute i produktion.
