### ISSUE TITLE
Inlämningar

### ISSUE THREAD

**Issue by rachel-zocom** [zocom-azomo/azomo#6]
Jag har fått feedback från ett par studenter att de hade svårt att lämna in sin uppgift i första kursen. 
Vissa hade fått uppdatera sidan och sedan sett att de hade lyckats lämna in, men andra skrev att de försökt fler gånger men att det
inte gick.

**Comment by zocom-johan-kivi** [comment]
Hmm, jag funderar på om det är relaterat till en annan bugg som gjorde att i vissa fall visade kurser från fe23 Karlstad också. Så kanske de varit inne på ”fel” kurs och försökt lämna in, vilket de inte får och då har det ”studsat”.

Den buggen är löst, så förhoppningsvis ska detta inte vara ett problem framöver.

Samma bugg förklarar att Johanna inte såg sin självskattning.

Ang hennes inlämning så la jag in den manuellt utifrån information i mailet, så nu finns den i Azomo! :D


Mvh

Johan Kivi
CTO @ ZoCom
073-333 97 80

10 sep. 2023 kl. 10:08 skrev rachel-zocom ***@***.***>:



Jag har fått feedback från ett par studenter att de hade svårt att lämna in sin uppgift i första kursen.
Vissa hade fått uppdatera sidan och sedan sett att de hade lyckats lämna in, men andra skrev att de försökt fler gånger men att det
inte gick.
