### ISSUE TITLE
kan ej uppdatera resurslänk

### ISSUE THREAD

**Issue by davidsvson** [zocom-azomo/azomo#61]
går inte ändra en länk i en resurs i en läraktivitet. Kommer upp grön ruta om att den uppdaterats men det har den inte.

**Comment by zocom-christoffer-wallenberg** [comment]
Efter närmare granskning, `payload` och `title` uppdateras i databasen men inte fältet `url` vilket är det som hämtas när man hämtar kursen. Oklart än så länge om det är FE eller BE (eller båda).

**Comment by zocom-johan-kivi** [comment]
Fixad och pushad till dev.
