### ISSUE TITLE
Bedömning, kommentarer till inlämning syns inte

### ISSUE THREAD

**Issue by lejonmanen** [zocom-azomo/azomo#62]
Flera studenter har lämnat in en URL och en kommentar, men det är bara URL:en som visas i lärarens bedömningsvy.

**Comment by zocom-christoffer-wallenberg** [comment]
`Comment` skickas inte med i API-anropet från frontend så inga kommentar kommer tillbaka från databasen.

**Comment by zocom-johan-kivi** [comment]
Fixat i senaste pushen.
