### ISSUE TITLE
Broken Layout "Mina Studier"

### ISSUE THREAD

**Issue by isakskold** [zocom-azomo/azomo#63]
**Describe the bug**
When I open a course the links for the other courses gets laid on top of the course I opened.

**To Reproduce**
1. Go to 'Mina Studier'
2. Click on 'Valfri kurs'
3. Scroll down to 'Längst ner på kursen du öppnade'

**Expected behavior**
Hade velat se länkar till de andra kurserna så som det är tänkt

**Screenshots**
![image](https://github.com/zocom-azomo/azomo/assets/149143560/8bd58ab0-994a-48f5-8dfa-442d89ba6a5d)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 120.0.6099.71 (Official Build) (64-bit)

**Additional context**
Du kan se längst ner på screenshoten att länkarna har lagt sig över där. De smälter in i bakgrunden ganska bra så kika noga. Om du kollar på "submit" knappen syns det väl vad jag menar. Har markerat vart felet är i dev tools på screenshoten också.

**Comment by isakskold** [comment]
Kan även lägga till att en förbättring hade också varit att man har möjligheten att minimera de kurser man öppnar. Det gör det enklare att navigera mellan kurserna utan att scrolla/uppdatera sidan. Just nu kan man bara öppna kurser I "Mina studier", men inte stänga dem igen om man vill snabbt öppna en annan kurs

**Comment by isakskold** [comment]
Försökte återskapa problemet och märkte att denna bug bara händer då jag öppnar html / css kursen. Ingen av de andra kurserna har denna bug när jag öppnar dem

**Comment by zocom-johan-kivi** [comment]
Det har nog att göra med att den innehåller många fler learningsgoals. Vi har pushat massa nya fixar. Testa nu! :D

**Comment by zocom-johan-kivi** [comment]
Fixad och pushad till dev.
