### ISSUE TITLE
Sortering av kurser tar inte hänsyn till årtal

### ISSUE THREAD

**Issue by justinhumane** [zocom-azomo/azomo#68]
**Describe the bug**
Sorteringen av kurser på sidan "Mina kurser" tar inte hänsyn till årtal. Enligt screenshot är kursen Agila metoder den första kurs vi gjorde.

**Expected behavior**
Listan med kurser borde sorteras i kronologisk ordning från utbildningens start till slut.

**Screenshots**
![image](https://github.com/zocom-azomo/azomo/assets/86984290/a2c82492-2780-4830-a559-af9d908625be)

**Comment by zocom-johan-kivi** [comment]
Fixad och pushad till dev.
