### ISSUE TITLE
Lägga till schema i outlook, inkl lektionsnamn och ev zoomlänk

### ISSUE THREAD

**Issue by jonasbondesson84** [zocom-azomo/azomo#7]
Det skulle vara smidigt att kunna få in schemat från sin kurs i sin outlook-kalender (och liknande). Just nu har jag fått lägga till den manuellt, men behöver i då ändra varje inlägg för att matcha lektionsinnehållet. Jag tycker att det är lättare att få en vecko-överblick i outlook än vad det är i Azomo (just nu).

**Comment by zocom-johan-kivi** [comment]
Tjena Jonas! Mycket bra ide! Denna funktion ligger redan med i vår "roadmap", men har ännu inte implementerats. En anledning är att planeringens detaljer ( ex. vilka aktiviteter ett lärområde innehåller ) inte finns på plats från början utan läggs till med någon veckas framförhållning. 

Skulle det vara lika värdefullt om endast livetillfällena och lärområdena (men inte aktiviteterna) var inlagda i kalendern?

**Comment by jonasbondesson84** [comment]
Absolut, det var nog lärområdena och live-tillfällerna jag menade. Aktiviteterna är inte lika viktigt, man kommer ju behöva gå in i Azomo ändå för att kunna göra självbedömningen. Härligt att ni har det i er roadmap!

**Comment by zocom-christoffer-wallenberg** [comment]
Nu finns det möjlighet att prenumerera på en kurs som synkas med din outlook - kalender. Öppna upp en ny feature request om något saknas!
