### ISSUE TITLE
omladdning av sidan krävs för att se satta betyg

### ISSUE THREAD

**Issue by davidsvson** [zocom-azomo/azomo#73]
går inte se vilka betyg som är satta förens sidan laddas om

**Comment by zocom-johan-kivi** [comment]
Kan ej återskapa, får gräva lite till.

**Comment by zocom-christoffer-wallenberg** [comment]
Jag tror att det kan vara strul med refetchQueries i Apollo klienten som inte vill ibland.

**Comment by davidsvson** [comment]
I dev miljön kan jag inte sätta betyg alls. Får "kursbedömning skapad"-toast men ser inget satt betyg. Inte heller efter omladdning

**Comment by zocom-christoffer-wallenberg** [comment]
Testad och fungerar i dev så denna stängs. Får öppna upp en ny bugg om problemet kvarstår.
