### ISSUE TITLE
inget betygs sätts vid klick på betyg direkt i listan

### ISSUE THREAD

**Issue by davidsvson** [zocom-azomo/azomo#74]
Betyg highlightas när man hovrar och klickar men inget betg sätts.

Måste äppna och stänga modalen för varje student som ska betygsättas

**Comment by zocom-johan-kivi** [comment]
Bugg eller feature?

**Comment by davidsvson** [comment]
Jag skulle kalla det en bugg. Antingen måste highligtningen tas bort eller så tillåtes betygsättning på båda sätten.

**Comment by zocom-johan-kivi** [comment]
Då kikar jag på det imorgon.

**Comment by zocom-christoffer-wallenberg** [comment]
Redo för release.

**Comment by zocom-christoffer-wallenberg** [comment]
Pushad och ute i produktion.
