### ISSUE TITLE
Lärmål: layout fel 

### ISSUE THREAD

**Issue by davidsvson** [zocom-azomo/azomo#76]
Knappen färdigställ visas ovanpå övrig text:

MacOS, Chrome Version 121.0.6167.85 (Officiell version) (arm64)

![Skärmavbild 2024-02-02 kl  12 52 07](https://github.com/zocom-azomo/azomo/assets/6167993/a9315d56-4a4c-449b-9485-a093c1c1d105)

**Comment by zocom-johan-kivi** [comment]
Dublett med https://github.com/zocom-azomo/azomo/issues/71.
LIA-team satt på att fixa idag.

**Comment by zocom-johan-kivi** [comment]
Fixat och pushat. Kommer i nästa release.
