### ISSUE TITLE
Azomo feature request - Troj Andersen ifrån FE23

### ISSUE THREAD

**Issue by trojandersen** [zocom-azomo/azomo#8]
**Is your feature request related to a problem? Please describe.**
Hej Johan! jag har stört mig lite på en del saker i Azomo, så tänkte ta och skicka iväg lite idéer här
som du rekommenderade! :)

Tänker först på att buggreporten finns endast på Mina Studieresultat (azomo.io/me),
men saknas på Min Utbildning (azomo.io/program). Hade gärna sett det användas på båda subpages,
men även kontinuerligt över alla subpages om fler läggs in.

![image](https://github.com/zocom-azomo/azomo/assets/72800679/3a3595ea-4d5b-449a-8142-658c0efe9789)

Sen även på exemplet ovan så är övre delen av azomo.io/program onödigt stor innan man kan komma ner till
informationen man vill komma åt på sidan enligt min åsikt. Tänker man kan kanske ha en mycket mindre header som ger kursnamnet & kursID(om det är vad det kallas? tänker FE23 i vårt fall!). 

![image](https://github.com/zocom-azomo/azomo/assets/72800679/4c68f2ba-c48e-414c-9dc5-ab9c1b7c9b55)

Här är nedre sidan av azomo.io/program sidan, tänker att man kanske kan tydligare namnge resurserna med kortare titlar? Tycker själv det blir rätt stökigt att hitta vad man söker när varje resurs är en paragraf/fråga. Tänker att det blir lättare att snappa upp informationen man vill åt när man söker den. 

Till exempel;
"Nyfiken på vad du kommer lära dig? Här hittar du alla kursplaner i den ordning de genomförs."
Kan vara "Kursplan".

Kan förstå att en del av .pdf filerna är relaterade till Folkuniversitetet, och kanske inte är under ditt område, men
tänker att man kanske kan endast använda titlarna för .pdf filen som dem pekar till för mer klarhet?

Tänkte med om det går att default öppna .pdf filerna i webbläsaren istället för att ladda ner? Är inte tillräckligt kunnig
om det kanske är ett problem på min ände, men tänkte ändå höra med dig haha :)

Sen vet jag att du nämnde att du höll på att titta på att den visar dubletter av kurser längst ner, men hade annars
gärna sett att man kan bli navigerad till kurserna via denna sida!

![image](https://github.com/zocom-azomo/azomo/assets/72800679/01c83301-017f-4752-99d7-9a9c66e8654b)

Sen tänker jag här när man interagerar med hamburgarmenyn uppe till vänster att det är rätt abrupt att menyvalen
placeras i mitten av skärmen. Tänker att man istället hade kunnat placera menyvalen under hamburgarmenyn, så behöver
man inte heller dra musen till mitten av sidan istället för att få åtkomst till valen direkt.

Tänker även att man kan placera kontoinformationen tillsammans med "logga ut" uppe till höger av sidan? Känns mycket mer
naturligt att ha det samlat där, och tror många känner det rätt naturligt att söka sig till det övre högra hörnet när det handlar om kontoinformation, inställningar m.m.!

Hoppas det inte blev alltför långradigt, men blev väl lite inspirerad att tänka på det mer nu, utifrån ett UX-design perspektiv!
Gillar annars väldigt mycket att ni skapat en egen läroplattform, och gillar skarpt att den är väldigt klinisk! Hoppas att feedbacken
var konstruktiv, och förstår såklart att alla har olika åsikter på sånt här med!

Ser fram emot att se mer hur utvecklingen av Azomo går, men även att själv lära mig mer kring UX-design!

Mvh,
Troj Andersen
FE23

**Comment by zocom-johan-kivi** [comment]
Tack för all feedback Troj! Ska ta tag i dessa förbättringar så fort jag får tid!

**Comment by zocom-johan-kivi** [comment]
Redesignad programvy i 2.1! Kika in! :D

**Comment by trojandersen** [comment]
Bra jobbat, ser bra ut! :)
