### ISSUE TITLE
Kan inte öppna bedömningsfliken på en kurs

### ISSUE THREAD

**Issue by zocom-christoffer-wallenberg** [zocom-azomo/azomo#80]
När jag går in på en kurs som lärare och väljer _Bedömning_ så står den bara och laddar, se bild nedan.

<img width="938" alt="Skärmavbild 2024-02-20 kl  09 24 26" src="https://github.com/zocom-azomo/azomo/assets/54267140/585305a6-3f20-4890-89cc-6a594297fa25">

**Comment by NguyenRobin** [comment]
https://github.com/zocom-azomo/azomo-backend/issues/588

**Comment by zocom-johan-kivi** [comment]
löst och pushad till prod
