### ISSUE TITLE
Som lärare kan jag inte skapa synkrona events

### ISSUE THREAD

**Issue by zocom-christoffer-wallenberg** [zocom-azomo/azomo#81]
I planeringsvyn för en kurs kan jag som lärare inte skapa ett synkront event på vänstersidan utan får felmeddelandet `Unsupported type passed`, se bild nedan.
<img width="390" alt="Skärmavbild 2024-02-20 kl  10 47 59" src="https://github.com/zocom-azomo/azomo/assets/54267140/a3ff8de4-1d05-4636-9c64-61017f32397f">

**Comment by zocom-christoffer-wallenberg** [comment]
För upp ett nytt felmeddelande nu, se bild nedan.
<img width="369" alt="Skärmavbild 2024-02-20 kl  13 21 04" src="https://github.com/zocom-azomo/azomo/assets/54267140/f60b25ea-dd97-4f1e-b442-d2837977a1dd">

**Comment by zocom-johan-kivi** [comment]
fixad och pushad till production.
