### ISSUE TITLE
Får upp studenter som inte tillhör kursen i bedömningsvyn

### ISSUE THREAD

**Issue by zocom-christoffer-wallenberg** [zocom-azomo/azomo#82]
Som lärare får jag upp i min kurs **Examensarbete** i utbildningen **JS22**, 252 studenter vilket verkar vara studenter från flera utbildningar. Jag borde enbart få studenterna som tillhör min utbildning, se bild nedan.
<img width="957" alt="Skärmavbild 2024-02-20 kl  11 11 13" src="https://github.com/zocom-azomo/azomo/assets/54267140/e2c931ad-f6aa-4ca7-b71b-987c7e4c82d1">

**Comment by zocom-christoffer-wallenberg** [comment]
Detta verkar vara ett problem i alla kurser oavsett utbildning.

**Comment by zocom-johan-kivi** [comment]
Fixad och pushad till dev.
