### ISSUE TITLE
Sortera kurser

### ISSUE THREAD

**Issue by Lennstorm** [zocom-azomo/azomo#83]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when jag går in på kursöversikten "Mina studier" och ska gå in på t.ex. nuvarande kurs och kurserna är sorterade
i nummerordning, men nummerordningen stämmer inte med kronologin. Nuvarande kurser är nummer 3 och 4 av 6 enligt listan, men rent kronologiskt nummer 5 och 6.

**Describe the solution you'd like**
Numrera och sortera kurserna i kronologisk ordning! Tack.

**Describe alternatives you've considered**
Alternativt lägg till sorteringsfunktion på rubrikerna så användaren själv kan sortera godtyckligt, men det låter krångligare.

**Additional context**
Screnshot:
![image](https://github.com/zocom-azomo/azomo/assets/143515549/f5cf8dd5-c403-4b5a-8081-169a17ecc491)

**Comment by zocom-johan-kivi** [comment]
Fixad. Kommer i nästa release.
