### ISSUE TITLE
Bug Kursmål

### ISSUE THREAD

**Issue by JuliaGloggPete** [zocom-azomo/azomo#84]
**Describe the bug**
![Skärmavbild 2024-02-20 kl  12 49 07](https://github.com/zocom-azomo/azomo/assets/113100420/abdf07ad-ce18-4103-96ef-1d0f9570b8a9)
Kursmålen om längre syns inte helt och man kan ej klicka heller för att se hela

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by zocom-johan-kivi** [comment]
fixat och pushat till produktion.
