### ISSUE TITLE
länker från biblioteket funkar ej 

### ISSUE THREAD

**Issue by JuliaGloggPete** [zocom-azomo/azomo#86]
**Describe the bug**
när jag drycker på videon så kommer det att videon inte finns 
![Skärmavbild 2024-02-20 kl  13 46 17](https://github.com/zocom-azomo/azomo/assets/113100420/1e3bd7c1-7687-4728-900c-b3de4d43313d)

**To Reproduce**
go till videobiblioteket - jag har provat med videos från MA22- Android utveckling

**Expected behavior**
get the video

**Comment by zocom-johan-kivi** [comment]
Funkar videorna om man klickar i kursvyn? Tycker länkarna ser lite konstiga ut.

**Comment by JuliaGloggPete** [comment]
det är bara android videonar som ej är korrekt länkat, de andra testade jag nu de funkar men MA22 Androidutveckling leder till ovan sida - från videoarkivet, men öven från kursvyn ledar de till samma tomma sida.

i den tidigare collection finns de dock så där kan jag kika på den

**Comment by zocom-johan-kivi** [comment]
Kanske något @davidsvson  kan kika på?

**Comment by davidsvson** [comment]
det är fel på länkarna så det är inte azomos fel 😑. Jag ändrade på rättigheterna någon gång och då ändrar vimeo på adressen till videorna, så dom går inte att komma åt via de gamla länkarna
