### ISSUE TITLE
Kan inte uppdatera VG-kriterier

### ISSUE THREAD

**Issue by zocom-christoffer-wallenberg** [zocom-azomo/azomo#87]
Jag kan lägga till ett VG-kriterie men när jag sedan klickar på detta och vill ändra texten får jag felmeddelandet `"Assessment criteria not found."` och kursmålet blir ej uppdaterat.

Felmeddelandet kommer från `updateAssessmentCriteria`.

**Comment by zocom-johan-kivi** [comment]
Du menar lärmål för VG? Annars lyckas jag inte återskapa buggen i dev.

**Comment by zocom-christoffer-wallenberg** [comment]
> Du menar lärmål för VG? Annars lyckas jag inte återskapa buggen i dev.

Ja det stämmer 👍

**Comment by zocom-johan-kivi** [comment]
Fixad och pushad till dev.
