### ISSUE TITLE
När jag som lärare skapar ett event blir starttiden kl 02:00

### ISSUE THREAD

**Issue by zocom-christoffer-wallenberg** [zocom-azomo/azomo#88]
När jag som lärare skapar ett event blir starttiden kl 02:00, den borde som default välja kl 09:00.

**Comment by zocom-christoffer-wallenberg** [comment]
Redo för release.

**Comment by lejonmanen** [comment]
Den borde även välja 16:00 som sluttid.

**Comment by zocom-christoffer-wallenberg** [comment]
Pushad och ute i produktion.
