### ISSUE TITLE
Prenumerera på kalender funkar inte

### ISSUE THREAD

**Issue by Lennstorm** [zocom-azomo/azomo#91]
**Describe the bug**
Har försökt lägga till kurskalendrarna både i gmail och outlook.
Verkar inte funka.

**To Reproduce**
1. Go to 'kurssida'
2. Click on 'prenumerera på kalender'
3. klistra in i privat kalender

**Expected behavior**
Kalendern borde läggas till.

**Screenshots**
![image](https://github.com/zocom-azomo/azomo/assets/143515549/aa0239d3-e981-4358-b195-3dcaf9311054)

**Desktop (please complete the following information):**
 - OS: Windows 11(?)
 - Browser Chrome, Edge. provat bägge

**Additional context**

**Comment by zocom-christoffer-wallenberg** [comment]
Redo för release.

**Comment by zocom-christoffer-wallenberg** [comment]
- [ ] Release the kraken!

**Comment by zocom-christoffer-wallenberg** [comment]
Fix finns i produktion.
