### ISSUE TITLE
Let´s uppskatta är grönt

### ISSUE THREAD

**Issue by GitMicaFri** [zocom-azomo/azomo#97]
![Capture](https://github.com/zocom-azomo/azomo/assets/142665994/507e72be-6749-4720-aae0-20366f004009)

Let´s uppskatta vad jag lärt mig är grön och det står självskattning klar på nästan alla moduler, fast vi inte ens gjort dessa.

Windows 10, Chrome

**Comment by zocom-christoffer-wallenberg** [comment]
Felet uppstår när det inte finns några lärmål eller läraktiviteter på ett lärområde och eftersom det inte finns något att självuppskatta så står det "Självskattning klar". Alla lärområden ska ha minst ett lärmål och en aktivitet så detta beror egentligen på felaktig användning i Azomo.

**Comment by zocom-christoffer-wallenberg** [comment]
Fix finns i produktion.
